apiVersion: v1
kind: Service
metadata:
  name: {{ template "client.fullname" . }}
  labels:
    app: {{ template "client.name" . }}
    chart: {{ template "client.chart" . }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.deployment.http.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ template "client.name" . }}
