//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var Egress = &struct {
	StreamTypeHls    postgres.StringExpression
	StreamTypeWebrtc postgres.StringExpression
}{
	StreamTypeHls:    postgres.NewEnumValue("STREAM_TYPE_HLS"),
	StreamTypeWebrtc: postgres.NewEnumValue("STREAM_TYPE_WEBRTC"),
}
