version: "3.9"

networks:
  bridge:

services:

  nats:
    image: nats:alpine3.18
    command:
     - "-js"
    ports:
     - "4222:4222"
     - "8222:8222"
     - "6222:6222"
    networks:
        - bridge

  stream-pg:
    image: postgres:15.4-alpine3.18
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    ports:
      - 5432:5432
    networks:
        - bridge

  identity-pg:
    image: postgres:15.4-alpine3.18
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    ports:
      - 5433:5432
    networks:
        - bridge
