apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: 'identity-postgres-data-pvc'
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: 'stream-postgres-data-pvc'
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
