
image:
  registry: k3d-stream-platform-registry:5000
  name: services/stream
  tag: latest

service:
  type: LoadBalancer

deployment:
  http:
    port: 8082

http:
  port: 8082
  host: "0.0.0.0"

# psql -U user -p 5432 postgres
database:
  image: postgres:15.4-alpine3.18
  port: 5432
  username: "user"
  password: "password"
  name: "postgres"

ingestOperator:
  host: stream-platform-ingest-operator.default.svc.cluster.local
  port: 9191

identity:
  publicKeyService:
    host: stream-platform-identity.default.svc.cluster.local
    port: 9093

job:
  migrate:
    image:
      registry: k3d-stream-platform-registry:5000
      name: cmd/migrate
      tag: latest
