# permissions for end users to view ingesttemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: ingesttemplate-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ingestion-operator
    app.kubernetes.io/part-of: ingestion-operator
    app.kubernetes.io/managed-by: kustomize
  name: ingesttemplate-viewer-role
rules:
- apiGroups:
  - romashorodok.github.io
  resources:
  - ingesttemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - romashorodok.github.io
  resources:
  - ingesttemplates/status
  verbs:
  - get
