//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type RefreshTokens struct {
	ID           uuid.UUID `sql:"primary_key"`
	PrivateKeyID uuid.UUID
	Plaintext    string
	CreatedAt    time.Time
	ExpiresAt    time.Time
}
