//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

// UseSchema sets a new schema name for all generated table SQL builder types. It is recommended to invoke
// this method only once at the beginning of the program.
func UseSchema(schema string) {
	PrivateKeys = PrivateKeys.FromSchema(schema)
	RefreshTokens = RefreshTokens.FromSchema(schema)
	SchemaMigrations = SchemaMigrations.FromSchema(schema)
	UserPrivateKeys = UserPrivateKeys.FromSchema(schema)
	UserRefreshTokens = UserRefreshTokens.FromSchema(schema)
	Users = Users.FromSchema(schema)
}
