apiVersion: v2

name: stream-platform

description: A Helm chart of stream-platform for Kubernetes

type: application

version: 0.1.0

appVersion: "1.16.0"

dependencies:
- name: ingest
  version: 0.1.0
  repository: "file://services/ingest"
