apiVersion: v1
kind: Secret
metadata:
  name: '{{ template "identity.fullname" . }}-secret'
type: Opaque
stringData:
  postgresHost: '{{ template "identity.fullname" . }}-postgres.default.svc.cluster.local'

