apiVersion: v1
kind: Service
metadata:
  name: {{ template "identity.fullname" . }}
  labels:
    app: {{ template "identity.name" . }}
    chart: {{ template "identity.chart" . }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.deployment.http.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ template "identity.name" . }}
---
apiVersion: v1
kind: Service
metadata:
  name: '{{ template "identity.fullname" . }}-postgres'
  labels:
    app: '{{ template "identity.name" . }}-postgres'
    chart: {{ template "identity.chart" . }}
    release: {{ .Release.Name }}
spec:
  # NOTE: This is make headless service. It's so important to establish stable and fast database connection. It's load balance through the DNS by round-robin istread of service proxy
  clusterIP: None
  ports:
    - port: {{ .Values.database.port }}
      protocol: TCP
      name: postgres
  selector:
    app: '{{ template "identity.name" . }}-postgres'
