apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "ingest.fullname" . }}
  labels:
    app: {{ template "ingest.name" . }}
    chart: {{ template "ingest.chart" . }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ template "ingest.name" . }}
  template:
    metadata:
      labels:
        app: {{ template "ingest.name" . }}
    spec:
      containers:
        - name: {{ template "ingest.name" . }}
          image: {{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
          ports:
           - containerPort: {{ .Values.deployment.http.port }}
             protocol: {{ .Values.deployment.http.protocol }}
             name: http
           - containerPort: {{ .Values.deployment.webrtc.port }}
             protocol: {{ .Values.deployment.webrtc.protocol }}
             name: webrtc 
      
