apiVersion: v1
kind: Secret
metadata:
  name: '{{ template "ingest.fullname" . }}-secet-tests'
type: Opaque
stringData:
  whipEndpoint: 'http://{{ template "ingest.fullname" . }}.default.svc.cluster.local:8089/api/consumer/whip'

