package variables

import "github.com/google/uuid"

const (
	INGEST_BROADCASTER_ID = "INGEST_BROADCASTER_ID"
	INGEST_USERNAME       = "INGEST_USERNAME"
	INGEST_NAT_PUBLIC_IP  = "INGEST_NAT_PUBLIC_IP"
	INGEST_UDP_PORT       = "INGEST_UDP_PORT"
	INGEST_TCP_PORT       = "INGEST_TCP_PORT"
	INGEST_PORT_MIN       = "INGEST_PORT_MIN"
	INGEST_PORT_MAX       = "INGEST_PORT_MAX"

	NATS_HOST = "NATS_HOST"
	NATS_PORT = "NATS_PORT"

	TURN_ENABLE   = "TURN_ENABLE"
	TURN_URL      = "TURN_URL"
	TURN_USERNAME = "TURN_USER"
	TURN_PASSWORD = "TURN_PASSWORD"
)

const (
	INGEST_USERNAME_DEFAULT      = "admin"
	INGEST_NAT_PUBLIC_IP_DEFAULT = "127.0.0.1"
	INGEST_UDP_PORT_DEFAULT      = "3478"
	INGEST_TCP_PORT_DEFAULT      = "3478"
	INGEST_PORT_MIN_DEFAULT      = "20000"
	INGEST_PORT_MAX_DEFAULT      = "20099"

	NATS_HOST_DEFAULT  = "0.0.0.0"
	NATS_HOST_HEADLESS = "nats-release-headless.nats-system.svc.cluster.local"
	NATS_PORT_DEFAULT  = "4222"

	TURN_ENABLE_DEFAULT   = "false"
	TURN_URL_DEFAULT      = "turn:udp-gateway.default.svc.cluster.local:3478"
	TURN_USERNAME_DEFAULT = "user-1"
	TURN_PASSWORD_DEFAULT = "pass-1"
)

var INGEST_BROADCASTER_ID_DEFAULT = uuid.NullUUID{}.UUID.String()
