package variables

var (
	STREAM_INGEST_TEMPLATE = "STREAM_INGEST_TEMPLATE"

	STREAM_STANDALONE                   = "STREAN_STANDALONE"
	STREAM_STANDALONE_INGEST_URI        = "STREAM_STANDALONE_INGEST_URI"
	STREAM_STANDALONE_INGEST_DEPLOYMENT = "STREAM_STANDALONE_INGEST_DEPLOYMENT"
	STREAM_STANDALONE_INGEST_NAMESPACE  = "STREAM_STANDALONE_INGEST_NAMESPACE"
)

var (
	STREAM_INGEST_TEMPLATE_DEFAULT = "golang-ingest-template"

	STREAM_STANDALONE_DEFAULT                   = "true"
	STREAM_STANDALONE_INGEST_URI_DEFAULT        = "http://localhost:8089"
	STREAM_STANDALONE_INGEST_DEPLOYMENT_DEFAULT = "admin"
	STREAM_STANDALONE_INGEST_NAMESPACE_DEFAULT  = "default"
)
