package variables

var (
	STREAM_HTTP_HOST = "STREAM_HTTP_HOST"
	STREAM_HTTP_PORT = "STREAM_HTTP_PORT"

	STREAM_INGEST_TEMPLATE = "STREAM_INGEST_TEMPLATE"

	STREAM_STANDALONE                   = "STREAN_STANDALONE"
	STREAM_STANDALONE_INGEST_URI        = "STREAM_STANDALONE_INGEST_URI"
	STREAM_STANDALONE_INGEST_DEPLOYMENT = "STREAM_STANDALONE_INGEST_DEPLOYMENT"
	STREAM_STANDALONE_INGEST_NAMESPACE  = "STREAM_STANDALONE_INGEST_NAMESPACE"

	STREAM_IDENTITY_GRPC_PUBLIC_KEY_PORT = "STREAM_IDENTITY_GRPC_PUBLIC_KEY_PORT"
	STREAM_IDENTITY_GRPC_PUBLIC_KEY_HOST = "STREAM_IDENTITY_GRPC_PUBLIC_KEY_HOST"
)

var (
	STREAM_HTTP_HOST_DEFAULT = "0.0.0.0"
	STREAM_HTTP_PORT_DEFAULT = "8082"

	STREAM_INGEST_TEMPLATE_DEFAULT = "golang-ingest-template"

	STREAM_STANDALONE_DEFAULT                   = "true"
	STREAM_STANDALONE_INGEST_URI_DEFAULT        = "http://localhost:8089"
	STREAM_STANDALONE_INGEST_DEPLOYMENT_DEFAULT = "admin"
	STREAM_STANDALONE_INGEST_NAMESPACE_DEFAULT  = "default"

	STREAM_IDENTITY_GRPC_PUBLIC_KEY_HOST_DEFAULT = "0.0.0.0"
	STREAM_IDENTITY_GRPC_PUBLIC_KEY_PORT_DEFAULT = "9093"
)
