//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type ActiveStreams struct {
	ID            uuid.UUID `sql:"primary_key"`
	Running       bool
	Deployed      bool
	BroadcasterID uuid.UUID
	Username      string
	Namespace     string
	Deployment    string
	StartAt       time.Time
}
