//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type Egress string

const (
	Egress_StreamTypeHls    Egress = "STREAM_TYPE_HLS"
	Egress_StreamTypeWebrtc Egress = "STREAM_TYPE_WEBRTC"
)

func (e *Egress) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "STREAM_TYPE_HLS":
		*e = Egress_StreamTypeHls
	case "STREAM_TYPE_WEBRTC":
		*e = Egress_StreamTypeWebrtc
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for Egress enum")
	}

	return nil
}

func (e Egress) String() string {
	return string(e)
}
